name: Bug report
description: Report something that isn't working correctly
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly.
      placeholder: "A clear description of the problem..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Click...
        3. See error
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "Operating System..."
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      render: bash
      placeholder: "Error messages, console output..."
